name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --audit false
      - name: Run linter
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Build production dependencies
        run: npm ci --production --audit false
      - name: Create docker images
        run: |
          docker build -t ghcr.io/fabulator/fitbit-weight:latest .
          docker push ghcr.io/fabulator/fitbit-weight:latest
